version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
      - "5672:5672" # RabbitMQ port
      - "15672:15672" # UI
    networks:
      - my_network

  service_a:
    build:
      context: .
      dockerfile: Dockerfile-service-a
    container_name: service_a
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
    ports:
      - "50051:50051"
    networks:
      - my_network

  service_b:
    build:
      context: .
      dockerfile: Dockerfile-service-b
    container_name: service_b
    depends_on:
      - rabbitmq
    networks:
      - my_network

  sender:
    build:
      context: .
      dockerfile: Dockerfile-sender
    container_name: sender
    depends_on:
      - rabbitmq
      - service_a
    stdin_open: true
    tty: true
    networks:
      - my_network

networks:
  my_network: