# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_a.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service_a.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fservice_a.proto\"\x07\n\x05\x45mpty\"$\n\x0cTimeResponse\x12\x14\n\x0c\x63urrent_time\x18\x01 \x01(\t\"\x1d\n\nSumRequest\x12\x0f\n\x07numbers\x18\x01 \x03(\x05\"\x1c\n\x0bSumResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x32S\n\x08ServiceA\x12%\n\x0cWhatTimeIsIt\x12\x06.Empty\x1a\r.TimeResponse\x12 \n\x03Sum\x12\x0b.SumRequest\x1a\x0c.SumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_a_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_TIMERESPONSE']._serialized_start=28
  _globals['_TIMERESPONSE']._serialized_end=64
  _globals['_SUMREQUEST']._serialized_start=66
  _globals['_SUMREQUEST']._serialized_end=95
  _globals['_SUMRESPONSE']._serialized_start=97
  _globals['_SUMRESPONSE']._serialized_end=125
  _globals['_SERVICEA']._serialized_start=127
  _globals['_SERVICEA']._serialized_end=210
# @@protoc_insertion_point(module_scope)
